# Generated by Django 4.1.5 on 2023-01-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=4, verbose_name='Год')),
                ('salary', models.CharField(default='', max_length=1000, verbose_name='зарплата специалиста техподдержки')),
            ],
        ),
    ]
