# Generated by Django 4.1.5 on 2023-01-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=4, verbose_name='Год')),
                ('count', models.CharField(default='', max_length=1000, verbose_name='Количество вакансий')),
            ],
        ),
        migrations.CreateModel(
            name='TableGeoS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(default='', verbose_name='Город')),
                ('salary', models.CharField(default='', max_length=1000, verbose_name='Зарплаты')),
            ],
        ),
        migrations.CreateModel(
            name='TableGeoV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(default='', verbose_name='Город')),
                ('perc', models.CharField(default='', max_length=1000, verbose_name='Доля вакансий в %')),
            ],
        ),
        migrations.CreateModel(
            name='TableSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=4, verbose_name='Год')),
                ('skills', models.TextField(default='', verbose_name='Топ 10 навыков')),
            ],
        ),
        migrations.RenameModel(
            old_name='Table_salary',
            new_name='TableSalary',
        ),
    ]
