# Generated by Django 4.1.5 on 2023-01-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_index_tablecount_count_tech_tablesalary_salary_tech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='title1',
            field=models.CharField(default='1214141', max_length=1000, verbose_name='Описание'),
        ),
    ]
