# Generated by Django 4.1.5 on 2023-01-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_demand_demand_graph'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demand_graph',
            new_name='Demand',
        ),
    ]
