# Generated by Django 4.1.5 on 2023-01-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='title1',
            field=models.CharField(default=None, max_length=1000, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='geography',
            name='title1',
            field=models.CharField(default=None, max_length=1000, verbose_name='Описание'),
        ),
    ]
