# Generated by Django 4.1.5 on 2023-01-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_demand_title1_geography_title1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='title1',
            field=models.CharField(default='Востребованность', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='title1',
            field=models.CharField(default='География', max_length=1000, verbose_name='Описание'),
        ),
    ]
