# Generated by Django 4.1.5 on 2023-01-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_demand_title1_alter_geography_title1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='geography',
            name='title1',
        ),
    ]
