# Generated by Django 4.1.5 on 2023-01-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_demand_title1_geography_title1'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='image2',
            field=models.CharField(default=None, max_length=1000, verbose_name='график'),
        ),
        migrations.AddField(
            model_name='skills',
            name='image3',
            field=models.CharField(default=None, max_length=1000, verbose_name='график'),
        ),
        migrations.AddField(
            model_name='skills',
            name='image4',
            field=models.CharField(default=None, max_length=1000, verbose_name='график'),
        ),
        migrations.AddField(
            model_name='skills',
            name='image5',
            field=models.CharField(default=None, max_length=1000, verbose_name='график'),
        ),
        migrations.AddField(
            model_name='skills',
            name='image6',
            field=models.CharField(default=None, max_length=1000, verbose_name='график'),
        ),
        migrations.AddField(
            model_name='skills',
            name='image7',
            field=models.CharField(default=None, max_length=1000, verbose_name='график'),
        ),
        migrations.AddField(
            model_name='skills',
            name='image8',
            field=models.CharField(default=None, max_length=1000, verbose_name='график'),
        ),
    ]
