# Generated by Django 4.1.5 on 2023-01-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_skills_image2_skills_image3_skills_image4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='image1',
            field=models.CharField(default=None, max_length=1000, verbose_name='график1'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image2',
            field=models.CharField(default=None, max_length=1000, verbose_name='график2'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image3',
            field=models.CharField(default=None, max_length=1000, verbose_name='график3'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image4',
            field=models.CharField(default=None, max_length=1000, verbose_name='график4'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image5',
            field=models.CharField(default=None, max_length=1000, verbose_name='график5'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image6',
            field=models.CharField(default=None, max_length=1000, verbose_name='график6'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image7',
            field=models.CharField(default=None, max_length=1000, verbose_name='график7'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image8',
            field=models.CharField(default=None, max_length=1000, verbose_name='график8'),
        ),
    ]
