# Generated by Django 4.1.5 on 2023-01-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_skills_image1_alter_skills_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='image1',
            new_name='graph1',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='image2',
            new_name='graph2',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='image3',
            new_name='graph3',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='image4',
            new_name='graph4',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='image5',
            new_name='graph5',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='image6',
            new_name='graph6',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='image7',
            new_name='graph7',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='image8',
            new_name='graph8',
        ),
    ]
