# Generated by Django 4.1.5 on 2023-01-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_image1_skills_graph1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='title1',
            field=models.CharField(default=None, max_length=1000, verbose_name='Описание'),
        ),
    ]
